name = "lean-playground"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "nat"

[[lean_lib]]
name = "add"

[[lean_lib]]
name = "mult"

[[lean_lib]]
name = "nat_equiv"

[[lean_exe]]
name = "main"
